##### 2.1 数据操作

In [20]:
from mxnet import nd
import mxnet as mx

In [2]:
x = nd.arange(12)

In [3]:
x.shape

(12,)

In [4]:
# 查看方法帮助
help(nd.random.exponential)

Help on function exponential in module mxnet.ndarray.random:

exponential(scale=1, shape=_Null, dtype=_Null, ctx=None, out=None, **kwargs)
    Draw samples from an exponential distribution.
    
    Its probability density function is
    
    .. math:: f(x; \frac{1}{\beta}) = \frac{1}{\beta} \exp(-\frac{x}{\beta}),
    
    for x > 0 and 0 elsewhere. \beta is the scale parameter, which is the
    inverse of the rate parameter \lambda = 1/\beta.
    
    Parameters
    ----------
    scale : float or NDArray, optional
        The scale parameter, \beta = 1/\lambda.
    shape : int or tuple of ints, optional
        The number of samples to draw. If shape is, e.g., `(m, n)` and `scale` is
        a scalar, output shape will be `(m, n)`. If `scale`
        is an NDArray with shape, e.g., `(x, y)`, then output will have shape
        `(x, y, m, n)`, where `m*n` samples are drawn for each entry in `scale`.
    dtype : {'float16', 'float32', 'float64'}, optional
        Data type of output 

In [12]:
d = nd.zeros((1,2))

In [11]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.



In [13]:
nd.ones_like(d)


[[1. 1.]]
<NDArray 1x2 @cpu(0)>

In [15]:
help(nd.one_hot)

Help on function one_hot:

one_hot(indices=None, depth=_Null, on_value=_Null, off_value=_Null, dtype=_Null, out=None, name=None, **kwargs)
    Returns a one-hot array.
    
    The locations represented by `indices` take value `on_value`, while all
    other locations take value `off_value`.
    
    `one_hot` operation with `indices` of shape ``(i0, i1)`` and `depth`  of ``d`` would result
    in an output array of shape ``(i0, i1, d)`` with::
    
      output[i,j,:] = off_value
      output[i,j,indices[i,j]] = on_value
    
    Examples::
    
      one_hot([1,0,2,0], 3) = [[ 0.  1.  0.]
                               [ 1.  0.  0.]
                               [ 0.  0.  1.]
                               [ 1.  0.  0.]]
    
      one_hot([1,0,2,0], 3, on_value=8, off_value=1,
              dtype='int32') = [[1 8 1]
                                [8 1 1]
                                [1 1 8]
                                [8 1 1]]
    
      one_hot([[1,0],[1,0],[2,0]], 3) = [[

In [17]:
help(nd.random.normal)

Help on function normal in module mxnet.ndarray.random:

normal(loc=0, scale=1, shape=_Null, dtype=_Null, ctx=None, out=None, **kwargs)
    Draw random samples from a normal (Gaussian) distribution.
    
    Samples are distributed according to a normal distribution parametrized
    by *loc* (mean) and *scale* (standard deviation).
    
    
    Parameters
    ----------
    loc : float or NDArray, optional
        Mean (centre) of the distribution.
    scale : float or NDArray, optional
        Standard deviation (spread or width) of the distribution.
    shape : int or tuple of ints, optional
        The number of samples to draw. If shape is, e.g., `(m, n)` and `loc` and
        `scale` are scalars, output shape will be `(m, n)`. If `loc` and `scale`
        are NDArrays with shape, e.g., `(x, y)`, then output will have shape
        `(x, y, m, n)`, where `m*n` samples are drawn for each `[loc, scale)` pair.
    dtype : {'float16', 'float32', 'float64'}, optional
        Data type o

#### 2.2 矩阵基本运算

In [24]:
# gpu的随机矩阵
X = mx.nd.random.normal(0, 1, (2,3), ctx=mx.gpu(0))

In [25]:
Y = mx.nd.random.normal(0, 1, (2,3), ctx=mx.gpu(0))

In [26]:
print(X, Y)


[[-1.3607211   0.74679667  0.37808618]
 [ 1.3020267   0.5443981  -0.5725043 ]]
<NDArray 2x3 @gpu(0)> 
[[-0.9246624   0.9911375  -0.4820686 ]
 [-0.61760885  0.18082583 -0.15363811]]
<NDArray 2x3 @gpu(0)>


In [27]:
X + Y


[[-2.2853835   1.7379341  -0.10398242]
 [ 0.6844179   0.72522396 -0.7261424 ]]
<NDArray 2x3 @gpu(0)>

In [28]:
X - Y


[[-0.4360587  -0.24434084  0.86015475]
 [ 1.9196355   0.3635723  -0.41886616]]
<NDArray 2x3 @gpu(0)>

In [29]:
X * Y


[[ 1.2582077   0.74017817 -0.18226348]
 [-0.80414325  0.09844124  0.08795848]]
<NDArray 2x3 @gpu(0)>

In [30]:
X / Y


[[ 1.471587    0.75347435 -0.78429955]
 [-2.1081738   3.0106215   3.726317  ]]
<NDArray 2x3 @gpu(0)>

In [31]:
X.abs()


[[1.3607211  0.74679667 0.37808618]
 [1.3020267  0.5443981  0.5725043 ]]
<NDArray 2x3 @gpu(0)>

In [32]:
X.arccos() # 反余弦


[[       nan 0.72756404 1.1830683 ]
 [       nan 0.99512494 2.1803534 ]]
<NDArray 2x3 @gpu(0)>

In [33]:
nd.dot(X, X.T)


[[ 2.5522163 -1.5815965]
 [-1.5815965  2.3194041]]
<NDArray 2x2 @gpu(0)>

In [34]:
X.exp()


[[0.25647575 2.1102295  1.4594886 ]
 [3.676741   1.7235707  0.56411093]]
<NDArray 2x3 @gpu(0)>

In [42]:
nd.concat(X, Y, dim = 0)


[[-1.3607211   0.74679667  0.37808618]
 [ 1.3020267   0.5443981  -0.5725043 ]
 [-0.9246624   0.9911375  -0.4820686 ]
 [-0.61760885  0.18082583 -0.15363811]]
<NDArray 4x3 @gpu(0)>

In [39]:
nd.concat(X, Y, dim = 1)


[[-1.3607211   0.74679667  0.37808618 -0.9246624   0.9911375  -0.4820686 ]
 [ 1.3020267   0.5443981  -0.5725043  -0.61760885  0.18082583 -0.15363811]]
<NDArray 2x6 @gpu(0)>

In [40]:
X.shape

(2, 3)

In [43]:
X > Y


[[0. 0. 1.]
 [1. 1. 0.]]
<NDArray 2x3 @gpu(0)>

In [44]:
X < Y


[[1. 1. 0.]
 [0. 0. 1.]]
<NDArray 2x3 @gpu(0)>

In [45]:
X == Y


[[0. 0. 0.]
 [0. 0. 0.]]
<NDArray 2x3 @gpu(0)>

In [51]:
X.norm().asscalar() # 转换标量

2.2071748

In [52]:
X.asscalar()

ValueError: The current array is not a scalar

#### 2.3 广播机制

In [53]:
X + 1


[[-0.3607211   1.7467966   1.3780862 ]
 [ 2.3020267   1.5443981   0.42749572]]
<NDArray 2x3 @gpu(0)>

In [54]:
X * 2


[[-2.7214422   1.4935933   0.75617236]
 [ 2.6040535   1.0887963  -1.1450086 ]]
<NDArray 2x3 @gpu(0)>

In [55]:
A = nd.arange(3).reshape((3,1))

In [56]:
B = nd.arange(3).reshape((1, 2))

In [57]:
print(A, B)


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)> 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>


In [60]:
A / B


[[nan  0.]
 [inf  1.]
 [inf  2.]]
<NDArray 3x2 @cpu(0)>

#### 2.4 索引

In [61]:
X


[[-1.3607211   0.74679667  0.37808618]
 [ 1.3020267   0.5443981  -0.5725043 ]]
<NDArray 2x3 @gpu(0)>

In [66]:
X[0:,2]


[ 0.37808618 -0.5725043 ]
<NDArray 2 @gpu(0)>

#### 2.5 自动求导

In [67]:
from mxnet import autograd

In [83]:
X = nd.arange(4).reshape((4,1))

In [84]:
X


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [95]:
# 调用attach_grad申请存储梯度需要的内存
X.attach_grad()

In [96]:
# 记录计算算的梯度
with autograd.record():
    y = 2 * nd.dot(X.T, X)

In [97]:
y.backward()

In [100]:
assert (X.grad - 4 * X).norm().asscalar() == 0

In [101]:
X.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [102]:
print(autograd.is_training())

False


In [104]:
with autograd.record():
    print(autograd.is_training())

True


In [108]:
X.norm()


[3.7416573]
<NDArray 1 @cpu(0)>